// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW5-3ERUocdL-asEdY5WZiPcvGt7Kl_NI',
    appId: '1:604023343602:web:e7546de89f07d462f5836b',
    messagingSenderId: '604023343602',
    projectId: 'tuantn-magazine',
    authDomain: 'tuantn-magazine.firebaseapp.com',
    databaseURL: 'https://tuantn-magazine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuantn-magazine.appspot.com',
    measurementId: 'G-PPMDE47BJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6BS5FlEsbg3ZhKcP_wIa4JimLNhaSaEI',
    appId: '1:604023343602:android:de09e1b54551da09f5836b',
    messagingSenderId: '604023343602',
    projectId: 'tuantn-magazine',
    databaseURL: 'https://tuantn-magazine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuantn-magazine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfONVo1ZHyEtdLX88gDQCXQO8pakOkv3E',
    appId: '1:604023343602:ios:765a12ade433e561f5836b',
    messagingSenderId: '604023343602',
    projectId: 'tuantn-magazine',
    databaseURL: 'https://tuantn-magazine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuantn-magazine.appspot.com',
    iosBundleId: 'com.example.thigk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfONVo1ZHyEtdLX88gDQCXQO8pakOkv3E',
    appId: '1:604023343602:ios:765a12ade433e561f5836b',
    messagingSenderId: '604023343602',
    projectId: 'tuantn-magazine',
    databaseURL: 'https://tuantn-magazine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuantn-magazine.appspot.com',
    iosBundleId: 'com.example.thigk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW5-3ERUocdL-asEdY5WZiPcvGt7Kl_NI',
    appId: '1:604023343602:web:5249daed7bee90fff5836b',
    messagingSenderId: '604023343602',
    projectId: 'tuantn-magazine',
    authDomain: 'tuantn-magazine.firebaseapp.com',
    databaseURL: 'https://tuantn-magazine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tuantn-magazine.appspot.com',
    measurementId: 'G-2BMVT3QTDZ',
  );
}
